development:
  adapter: postgresql
  encoding: unicode
  database: image_hide_n_seek_development
  pool: 5
  username: kahaanpatel
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: image_hide_n_seek_test
  pool: 5
  username: kahaanpatel
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: image_hide_n_seek_production
  pool: 5
  username: kahaanpatel
  password:
